[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "COOKIE_SECRET"
client_id = "REPLACE WITH YOUR OWN GOOGLE OAUTH CLIENT_ID"
client_secret = "REPLACE WITH YOUR OWN GOOGLE OAUTH CLIENT_SECRET"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
